name: Clean Old Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  clean-old-releases:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete all releases except the latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting cleanup of old releases and tags..."
          
          # Get the latest release tag
          LATEST_RELEASE=$(gh release list --limit 1 | grep -v "No releases" | cut -f3)
          
          if [ -z "$LATEST_RELEASE" ]; then
            echo "No releases found. Nothing to clean up."
            exit 0
          fi
          
          echo "Latest release is: $LATEST_RELEASE (this will be kept)"
          
          # List all releases except the latest and delete them
          gh release list | grep -v TITLE | grep -v "$LATEST_RELEASE" | cut -f3 | while read -r tag; do
            if [ -n "$tag" ]; then
              echo "Deleting release with tag: $tag"
              gh release delete -y --cleanup-tag "$tag"
            fi
          done
          
          echo "Cleanup completed! Kept latest release: $LATEST_RELEASE"