name: Purge All Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  purge-releases:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Delete all releases and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting cleanup of all releases and tags..."
          
          # List all releases and process them
          gh release list | grep -v TITLE | cut -f3 | while read -r tag; do
            echo "Deleting release with tag: $tag"
            gh release delete -y --cleanup-tag "$tag"
          done
          
          echo "Cleanup completed!"